<?xml version="1.0"?>
<package format="3">
  <name>cmax_slam</name>
  <version>0.0.0</version>
  <description>CMax-SLAM: Event-based Rotational-Motion Bundle Adjustment and SLAM System using Contrast Maximization</description>
  <maintainer email="shuang.guo@campus.tu-berlin.de">Shuang Guo</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>event_camera_codecs</depend>
  <depend>image_geometry</depend>
  <depend>cv_bridge</depend>
  <depend>OpenCV</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
