<?xml version="1.0"?>
<package format="3">
  <name>cmax_slam</name>
  <version>0.0.0</version>
  <description>CMax-SLAM: Event-based Rotational-Motion Bundle Adjustment and SLAM System using Contrast Maximization</description>
  <maintainer email="shuang.guo@campus.tu-berlin.de">Shuang Guo</maintainer>


  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <depend>geometry_msgs</depend>
  
  <depend>opencv</depend>
  <depend>camera_info_manager</depend>

  <depend>event_camera_msgs</depend>
  <depend>event_camera_codecs</depend>

  <depend>gsl</depend>

  <depend>sensor_msgs</depend>
  <depend>ros_environment</depend>

  <!-- <depend>event_camera_msgs</depend>
  <depend>event_camera_codecs</depend>  
  <depend>image_transport</depend>
  <depend>sensor_msgs</depend>
  <depend>ros_environment</depend> -->
  


  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
